FAMILY  = artix7
PART = xc7a100tcsg324-1
BOARD   = arty7
JTAG_LINK = --board ${BOARD}
XDC = Arty-A7-100-Master.xdc
PROJECT = chip_balls
ADDITIONAL_SOURCES = tmds_encoder.v \
					my_vga_clk_generator.v \
					ball.v \
					hdmi_device.v \
					lfsr.v\

include ./openXC7.mk